// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Notification_System.Models;

[Table("Notification")]
public partial class Notification
{
    [Key]
    public int Id { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string Username { get; set; }

    [Required]
    [StringLength(1000)]
    [Unicode(false)]
    public string Message { get; set; }

    [Required]
    [StringLength(50)]
    [Unicode(false)]
    public string MessageType { get; set; }

    public DateOnly NotificationDateTime { get; set; }
}